/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as GoldSilverIndexRouteImport } from './routes/gold-silver/index'
import { Route as GoldSilverSlugRouteImport } from './routes/gold-silver/$slug'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as SoundMoneyIndexRouteImport } from './routes/sound-money/index'
import { Route as SoundMoneySlugRouteImport } from './routes/sound-money/$slug'
import { Route as HistoryClusterIndexRouteImport } from './routes/history/$cluster/index'
import { Route as HistoryClusterEpisodeRouteImport } from './routes/history/$cluster/$episode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldSilverIndexRoute = GoldSilverIndexRouteImport.update({
  id: '/gold-silver/',
  path: '/gold-silver/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldSilverSlugRoute = GoldSilverSlugRouteImport.update({
  id: '/gold-silver/$slug',
  path: '/gold-silver/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundMoneyIndexRoute = SoundMoneyIndexRouteImport.update({
  id: '/sound-money/',
  path: '/sound-money/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundMoneySlugRoute = SoundMoneySlugRouteImport.update({
  id: '/sound-money/$slug',
  path: '/sound-money/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryClusterIndexRoute = HistoryClusterIndexRouteImport.update({
  id: '/history/$cluster/',
  path: '/history/$cluster/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryClusterEpisodeRoute = HistoryClusterEpisodeRouteImport.update({
  id: '/history/$cluster/$episode',
  path: '/history/$cluster/$episode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/flows': typeof FlowsRoute
  '/maps': typeof MapsRoute
  '/gold-silver/$slug': typeof GoldSilverSlugRoute
  '/sound-money/$slug': typeof SoundMoneySlugRoute
  '/gold-silver/': typeof GoldSilverIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/sound-money/': typeof SoundMoneyIndexRoute
  '/history/$cluster/$episode': typeof HistoryClusterEpisodeRoute
  '/history/$cluster/': typeof HistoryClusterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/flows': typeof FlowsRoute
  '/maps': typeof MapsRoute
  '/gold-silver/$slug': typeof GoldSilverSlugRoute
  '/sound-money/$slug': typeof SoundMoneySlugRoute
  '/gold-silver': typeof GoldSilverIndexRoute
  '/history': typeof HistoryIndexRoute
  '/sound-money': typeof SoundMoneyIndexRoute
  '/history/$cluster/$episode': typeof HistoryClusterEpisodeRoute
  '/history/$cluster': typeof HistoryClusterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/flows': typeof FlowsRoute
  '/maps': typeof MapsRoute
  '/gold-silver/$slug': typeof GoldSilverSlugRoute
  '/sound-money/$slug': typeof SoundMoneySlugRoute
  '/gold-silver/': typeof GoldSilverIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/sound-money/': typeof SoundMoneyIndexRoute
  '/history/$cluster/$episode': typeof HistoryClusterEpisodeRoute
  '/history/$cluster/': typeof HistoryClusterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/flows'
    | '/maps'
    | '/gold-silver/$slug'
    | '/sound-money/$slug'
    | '/gold-silver/'
    | '/history/'
    | '/sound-money/'
    | '/history/$cluster/$episode'
    | '/history/$cluster/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desk'
    | '/flows'
    | '/maps'
    | '/gold-silver/$slug'
    | '/sound-money/$slug'
    | '/gold-silver'
    | '/history'
    | '/sound-money'
    | '/history/$cluster/$episode'
    | '/history/$cluster'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/flows'
    | '/maps'
    | '/gold-silver/$slug'
    | '/sound-money/$slug'
    | '/gold-silver/'
    | '/history/'
    | '/sound-money/'
    | '/history/$cluster/$episode'
    | '/history/$cluster/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRoute: typeof DeskRoute
  FlowsRoute: typeof FlowsRoute
  MapsRoute: typeof MapsRoute
  GoldSilverSlugRoute: typeof GoldSilverSlugRoute
  SoundMoneySlugRoute: typeof SoundMoneySlugRoute
  GoldSilverIndexRoute: typeof GoldSilverIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  SoundMoneyIndexRoute: typeof SoundMoneyIndexRoute
  HistoryClusterEpisodeRoute: typeof HistoryClusterEpisodeRoute
  HistoryClusterIndexRoute: typeof HistoryClusterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-silver/': {
      id: '/gold-silver/'
      path: '/gold-silver'
      fullPath: '/gold-silver/'
      preLoaderRoute: typeof GoldSilverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-silver/$slug': {
      id: '/gold-silver/$slug'
      path: '/gold-silver/$slug'
      fullPath: '/gold-silver/$slug'
      preLoaderRoute: typeof GoldSilverSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound-money/': {
      id: '/sound-money/'
      path: '/sound-money'
      fullPath: '/sound-money/'
      preLoaderRoute: typeof SoundMoneyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound-money/$slug': {
      id: '/sound-money/$slug'
      path: '/sound-money/$slug'
      fullPath: '/sound-money/$slug'
      preLoaderRoute: typeof SoundMoneySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$cluster/': {
      id: '/history/$cluster/'
      path: '/history/$cluster'
      fullPath: '/history/$cluster/'
      preLoaderRoute: typeof HistoryClusterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$cluster/$episode': {
      id: '/history/$cluster/$episode'
      path: '/history/$cluster/$episode'
      fullPath: '/history/$cluster/$episode'
      preLoaderRoute: typeof HistoryClusterEpisodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRoute: DeskRoute,
  FlowsRoute: FlowsRoute,
  MapsRoute: MapsRoute,
  GoldSilverSlugRoute: GoldSilverSlugRoute,
  SoundMoneySlugRoute: SoundMoneySlugRoute,
  GoldSilverIndexRoute: GoldSilverIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  SoundMoneyIndexRoute: SoundMoneyIndexRoute,
  HistoryClusterEpisodeRoute: HistoryClusterEpisodeRoute,
  HistoryClusterIndexRoute: HistoryClusterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
