/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as Googleb53ee24d705afe09DothtmlRouteImport } from './routes/googleb53ee24d705afe09[.]html'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GoldSilverIndexRouteImport } from './routes/gold-silver/index'
import { Route as GoldSilverSlugRouteImport } from './routes/gold-silver/$slug'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as MarketsIndexRouteImport } from './routes/markets/index'
import { Route as MarketsSlugRouteImport } from './routes/markets/$slug'
import { Route as SoundMoneyIndexRouteImport } from './routes/sound-money/index'
import { Route as SoundMoneySlugRouteImport } from './routes/sound-money/$slug'
import { Route as HistoryClusterIndexRouteImport } from './routes/history/$cluster/index'
import { Route as HistoryClusterEpisodeRouteImport } from './routes/history/$cluster/$episode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const Googleb53ee24d705afe09DothtmlRoute =
  Googleb53ee24d705afe09DothtmlRouteImport.update({
    id: '/googleb53ee24d705afe09.html',
    path: '/googleb53ee24d705afe09.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldSilverIndexRoute = GoldSilverIndexRouteImport.update({
  id: '/gold-silver/',
  path: '/gold-silver/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldSilverSlugRoute = GoldSilverSlugRouteImport.update({
  id: '/gold-silver/$slug',
  path: '/gold-silver/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/markets/',
  path: '/markets/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsSlugRoute = MarketsSlugRouteImport.update({
  id: '/markets/$slug',
  path: '/markets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundMoneyIndexRoute = SoundMoneyIndexRouteImport.update({
  id: '/sound-money/',
  path: '/sound-money/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundMoneySlugRoute = SoundMoneySlugRouteImport.update({
  id: '/sound-money/$slug',
  path: '/sound-money/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryClusterIndexRoute = HistoryClusterIndexRouteImport.update({
  id: '/history/$cluster/',
  path: '/history/$cluster/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryClusterEpisodeRoute = HistoryClusterEpisodeRouteImport.update({
  id: '/history/$cluster/$episode',
  path: '/history/$cluster/$episode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/desk': typeof DeskRoute
  '/flows': typeof FlowsRoute
  '/googleb53ee24d705afe09.html': typeof Googleb53ee24d705afe09DothtmlRoute
  '/maps': typeof MapsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gold-silver/$slug': typeof GoldSilverSlugRoute
  '/markets/$slug': typeof MarketsSlugRoute
  '/sound-money/$slug': typeof SoundMoneySlugRoute
  '/gold-silver/': typeof GoldSilverIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/markets/': typeof MarketsIndexRoute
  '/sound-money/': typeof SoundMoneyIndexRoute
  '/history/$cluster/$episode': typeof HistoryClusterEpisodeRoute
  '/history/$cluster/': typeof HistoryClusterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/desk': typeof DeskRoute
  '/flows': typeof FlowsRoute
  '/googleb53ee24d705afe09.html': typeof Googleb53ee24d705afe09DothtmlRoute
  '/maps': typeof MapsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gold-silver/$slug': typeof GoldSilverSlugRoute
  '/markets/$slug': typeof MarketsSlugRoute
  '/sound-money/$slug': typeof SoundMoneySlugRoute
  '/gold-silver': typeof GoldSilverIndexRoute
  '/history': typeof HistoryIndexRoute
  '/markets': typeof MarketsIndexRoute
  '/sound-money': typeof SoundMoneyIndexRoute
  '/history/$cluster/$episode': typeof HistoryClusterEpisodeRoute
  '/history/$cluster': typeof HistoryClusterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/desk': typeof DeskRoute
  '/flows': typeof FlowsRoute
  '/googleb53ee24d705afe09.html': typeof Googleb53ee24d705afe09DothtmlRoute
  '/maps': typeof MapsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gold-silver/$slug': typeof GoldSilverSlugRoute
  '/markets/$slug': typeof MarketsSlugRoute
  '/sound-money/$slug': typeof SoundMoneySlugRoute
  '/gold-silver/': typeof GoldSilverIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/markets/': typeof MarketsIndexRoute
  '/sound-money/': typeof SoundMoneyIndexRoute
  '/history/$cluster/$episode': typeof HistoryClusterEpisodeRoute
  '/history/$cluster/': typeof HistoryClusterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/desk'
    | '/flows'
    | '/googleb53ee24d705afe09.html'
    | '/maps'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/gold-silver/$slug'
    | '/markets/$slug'
    | '/sound-money/$slug'
    | '/gold-silver/'
    | '/history/'
    | '/markets/'
    | '/sound-money/'
    | '/history/$cluster/$episode'
    | '/history/$cluster/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/desk'
    | '/flows'
    | '/googleb53ee24d705afe09.html'
    | '/maps'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/gold-silver/$slug'
    | '/markets/$slug'
    | '/sound-money/$slug'
    | '/gold-silver'
    | '/history'
    | '/markets'
    | '/sound-money'
    | '/history/$cluster/$episode'
    | '/history/$cluster'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/desk'
    | '/flows'
    | '/googleb53ee24d705afe09.html'
    | '/maps'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/gold-silver/$slug'
    | '/markets/$slug'
    | '/sound-money/$slug'
    | '/gold-silver/'
    | '/history/'
    | '/markets/'
    | '/sound-money/'
    | '/history/$cluster/$episode'
    | '/history/$cluster/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DeskRoute: typeof DeskRoute
  FlowsRoute: typeof FlowsRoute
  Googleb53ee24d705afe09DothtmlRoute: typeof Googleb53ee24d705afe09DothtmlRoute
  MapsRoute: typeof MapsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GoldSilverSlugRoute: typeof GoldSilverSlugRoute
  MarketsSlugRoute: typeof MarketsSlugRoute
  SoundMoneySlugRoute: typeof SoundMoneySlugRoute
  GoldSilverIndexRoute: typeof GoldSilverIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
  SoundMoneyIndexRoute: typeof SoundMoneyIndexRoute
  HistoryClusterEpisodeRoute: typeof HistoryClusterEpisodeRoute
  HistoryClusterIndexRoute: typeof HistoryClusterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/googleb53ee24d705afe09.html': {
      id: '/googleb53ee24d705afe09.html'
      path: '/googleb53ee24d705afe09.html'
      fullPath: '/googleb53ee24d705afe09.html'
      preLoaderRoute: typeof Googleb53ee24d705afe09DothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-silver/': {
      id: '/gold-silver/'
      path: '/gold-silver'
      fullPath: '/gold-silver/'
      preLoaderRoute: typeof GoldSilverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-silver/$slug': {
      id: '/gold-silver/$slug'
      path: '/gold-silver/$slug'
      fullPath: '/gold-silver/$slug'
      preLoaderRoute: typeof GoldSilverSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/': {
      id: '/markets/'
      path: '/markets'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$slug': {
      id: '/markets/$slug'
      path: '/markets/$slug'
      fullPath: '/markets/$slug'
      preLoaderRoute: typeof MarketsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound-money/': {
      id: '/sound-money/'
      path: '/sound-money'
      fullPath: '/sound-money/'
      preLoaderRoute: typeof SoundMoneyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound-money/$slug': {
      id: '/sound-money/$slug'
      path: '/sound-money/$slug'
      fullPath: '/sound-money/$slug'
      preLoaderRoute: typeof SoundMoneySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$cluster/': {
      id: '/history/$cluster/'
      path: '/history/$cluster'
      fullPath: '/history/$cluster/'
      preLoaderRoute: typeof HistoryClusterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$cluster/$episode': {
      id: '/history/$cluster/$episode'
      path: '/history/$cluster/$episode'
      fullPath: '/history/$cluster/$episode'
      preLoaderRoute: typeof HistoryClusterEpisodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DeskRoute: DeskRoute,
  FlowsRoute: FlowsRoute,
  Googleb53ee24d705afe09DothtmlRoute: Googleb53ee24d705afe09DothtmlRoute,
  MapsRoute: MapsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GoldSilverSlugRoute: GoldSilverSlugRoute,
  MarketsSlugRoute: MarketsSlugRoute,
  SoundMoneySlugRoute: SoundMoneySlugRoute,
  GoldSilverIndexRoute: GoldSilverIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  MarketsIndexRoute: MarketsIndexRoute,
  SoundMoneyIndexRoute: SoundMoneyIndexRoute,
  HistoryClusterEpisodeRoute: HistoryClusterEpisodeRoute,
  HistoryClusterIndexRoute: HistoryClusterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
